version: '3.8'
services:
  postgres:
    image: postgres:14.5-alpine3.16
    restart: always
    environment:
      - POSTGRES_USER=rafi
      - POSTGRES_PASSWORD=passwordforhangry
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
  cache:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
volumes:
  postgres:
  cache: